# Generated by Django 4.1.3 on 2022-12-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Задайте тему', max_length=50, verbose_name='тема')),
                ('descripion', models.TextField(help_text='Опишите проблему', verbose_name='описание')),
                ('file', models.FileField(null=True, upload_to='files')),
                ('status', models.CharField(choices=[('RS', 'Решено'), ('UNRS', 'Не решено'), ('FZ', 'Заморожено')], default='UNRS', max_length=30, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'обращения',
            },
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Здесь Ваш текст', verbose_name='текст')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticketresponse', verbose_name='ответ')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='tickets.ticket', verbose_name='обращение')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'обращения',
            },
        ),
    ]
