# Generated by Django 4.1.3 on 2022-12-05 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responding', to=settings.AUTH_USER_MODEL, verbose_name='ответчик'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AddConstraint(
            model_name='ticketresponse',
            constraint=models.UniqueConstraint(fields=('ticket', 'message'), name='message_unique'),
        ),
    ]
