# Generated by Django 4.1.3 on 2022-12-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(1, 'Решено'), (2, 'Не решено'), (3, 'Заморожено')], default=2, max_length=30, verbose_name='статус'),
        ),
    ]
