# Generated by Django 4.1.3 on 2022-12-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'Клиент'), ('support', 'Поддержка'), ('admin', 'Администратор')], default='client', max_length=20),
        ),
    ]
